path:
  data_path: '../data/cifar-10/'
  result_path: results/VIT_cifar10/
  model_path: Network/VIT_Model_cifar10/
  public_path: '../data/cifar-100/val/'

patch:
  image_size: 224
  patch_size: 16
  num_patches: 196
  num_classes: 10
  nums_per_class: [5000, 1000]
  nums_per_class_train: 5000
  nums_per_class_val: 1000
  channels: 3
  fold_size: 64
  fold_patch_size: 8
  embed_dim: 384
  depth: 12
  heads: 12
  mlp_dim: 512
  dropout: 0
  emb_dropout: 0.1

general:
  dataset: CIFAR10
  use_cuda: Yes
  seed: 1001
  seed_target: 1234
  seed_shadow: 101
  public_data_seed: 404
  train_target_size: 30000 # 2 500, 5 000, 10 000, 15 000 // 4 600, 10 520, 19 920, 29 540
  test_target_size: 30000
  num_workers: 8
  mixup_alpha: 1
  cutmix_alpha: 1.0

#目前最优 128/0.00185
#可选 0.0016/0.0017/185

learning:
  batch_size: 128
#  learning_rate: 0.00185
  #dpsgd
  learning_rate: 0.0015
  min_lr: 0.00001
  momentum: 0.9
  epochs: 30 #25 max 100 cifar10, 200 sinon
  decrease_lr_factor: 0.1
  decrease_lr_every: 50
  weight_decay: 0.00005
  beta1: 0.9
  beta2: 0.99
  warmup_epoch: 5
  DDP: True
  DP: True
  atk_learning_rate: 0.001
  atk_epochs: 25
  val_epoch: True

mask:
    start: 138
    step: 12
    stop: 196
    warmup_epoch: 5
    mask_ratio: 0.5
    jigsaw: 0.5
    num_masking_patches: 8
    min_num_patches: 4
