import os
# os.system("python -m torch.distributed.launch --nnodes=1 --nproc_per_node=2 main.py --set 2")
# os.system("python -m torch.distributed.launch --nnodes=1 --nproc_per_node=2 main.py --nums 27")
# os.system("python -m torch.distributed.launch --nnodes=1 --nproc_per_node=2 main.py --nums 54")
# os.system("python -m torch.distributed.launch --nnodes=1 --nproc_per_node=2 main.py --nums 108")
os.system("python mia_attn.py --model ViT_mask_0.051.pth")
os.system("python mia_attn.py --model ViT_mask_0.255.pth")
os.system("python mia_attn.py --model ViT_mask_0.459.pth")
os.system("python mia_attn.py --model ViT_mask_0.663.pth")
os.system("python mia_attn.py --model ViT_mask_0.867.pth")