path:
  data_path: '../data/cifar-100/'
  result_path: results/VIT_cifar100/
  model_path: Network/VIT_Model_cifar100/
  public_path: '../data/cinic-10/test/'

patch:
  image_size: 32
  patch_size: 4
  window_size: 4
  num_patches: 16
  num_classes: 100
  nums_per_class: 6000
  embed_dim: 96
  depths: (2, 2, 6, 2)
  num_heads: (3, 6, 12, 24)
  mlp_dim: 512
  drop_rate: 0
  emb_dropout: 0.1

general:
  dataset: CIFAR100
  use_cuda: Yes
  seed: 1001
  seed_target: 1234
  seed_shadow: 101
  public_data_seed: 404
  train_target_size: 30000 # 2 500, 5 000, 10 000, 15 000 // 4 600, 10 520, 19 920, 29 540
  test_target_size: 30000
  num_workers: 0
  mixup_alpha: 0.8
  cutmix_alpha: 1.0
  DDP: False
  DP: True

learning:
  batch_size: 64
  learning_rate: 0.001
  momentum: 0.9
  epochs: 200 #25 max 100 cifar10, 200 sinon
  decrease_lr_factor: 1
  decrease_lr_every: 50
  weight_decay: 0

mask:
    warmup_epoch: 20
    jigsaw: 0.5
    num_masking_patches: 8
    min_num_patches: 4
