path:
  data_path: '../data/ImageNet100/'
  result_path: results/VIT_Model_imagenet100/
  model_path: Network/VIT_Model_imagenet100/
  public_path: '../data/ImageNet100/public/'

patch:
  image_size: 224
  patch_size: 4
  window_size: 7
  num_patches: 196
  num_classes: 100
  embed_dim: 96
  depth: (2, 2, 6, 2)
  heads: (3, 6, 12, 24)
  mlp_dim: 512
  dropout: 0.1
  emb_dropout: 0.1

general:
  type: mask_avg_fill
  use_cuda: Yes
  train_spilt_seed: 101
  dataset: cifar10
  train_target_size: 5000 # 2 500, 5 000, 10 000, 15 000 // 4 600, 10 520, 19 920, 29 540
  test_target_size: 2000
  number_shadow_model: 128 # 25 50 MNIST ou 100 cifar

learning:
  batch_size: 128
  learning_rate: 0.01
  momentum: 0.9
  epochs: 100 #25 max 100 cifar10, 200 sinon
  decrease_lr_factor: 0.5
  decrease_lr_every: 50
  ml:
    reg_lambd: 10
    n_estimators: 10000

mask:
    warmup_epoch: 20
    jigsaw: 0.5
    num_masking_patches: 8
    min_num_patches: 4
