path:
  data_path: '../data/fashion-mnist/'
  result_path: results/VIT_fashion-mnist/
  model_path: Network/VIT_Model_fashion-mnist/
  public_path: '../data/public/mnist/'

patch:
  image_size: 28
  patch_size: 4
  num_patches: 49
  num_classes: 10
  nums_per_class: [6000, 1000]
  nums_per_class_train: 6000
  nums_per_class_val: 1000
  channels: 1
  fold_size: 56
  fold_patch_size: 8
  embed_dim: 64
  depth: 6
  heads: 12
  mlp_dim: 512
  dropout: 0
  emb_dropout: 0.1

general:
  dataset: fashion-mnist
  use_cuda: Yes
  seed: 1001
  seed_target: 1234
  seed_shadow: 101
  public_data_seed: 404
  train_target_size: 30000 # 2 500, 5 000, 10 000, 15 000 // 4 600, 10 520, 19 920, 29 540
  test_target_size: 30000
  num_workers: 8
  mixup_alpha: 1
  cutmix_alpha: 1.0

learning:
  batch_size: 128
  learning_rate: 0.001
  min_lr: 0.00001
  momentum: 0.9
  epochs: 50
  decrease_lr_factor: 0.1
  decrease_lr_every: 50
  weight_decay: 0.00005
  beta1: 0.9
  beta2: 0.99
  warmup_epoch: 5
  DDP: True
  DP: True
  atk_learning_rate: 0.001
  atk_epochs: 25

mask:
    warmup_epoch: 20
    mask_ratio: 0.5
    jigsaw: 0.5
    num_masking_patches: 8
    min_num_patches: 2
