path:
  data_path: '../data/ImageNet10/'
  result_path: results/VIT_ImageNet10/
  model_path: Network/VIT_Model_ImageNet10/
  public_path: '../data/ImageNet100/public/'

patch:
  image_size: 224
  patch_size: 16
  window_size: 7
  num_patches: 196
  num_classes: 10
  nums_per_class: 1300
  nums_per_class_train: 700
  nums_per_class_val: 700
  embed_dim: 768
  depths: (2, 2, 6, 2)
  num_heads: (3, 6, 12, 24)
  mlp_dim: 512
  drop_rate: 0
  emb_dropout: 0.1

general:
  dataset: ImageNet10
  use_cuda: Yes
  seed: 1001
  seed_target: 1234
  seed_shadow: 101
  public_data_seed: 404
  train_target_size: 30000 # 2 500, 5 000, 10 000, 15 000 // 4 600, 10 520, 19 920, 29 540
  test_target_size: 30000
  num_workers: 8
  mixup_alpha: 0.8
  cutmix_alpha: 1.0

learning:
  batch_size: 128
  learning_rate: 0.001
  min_lr: 0.00001
  momentum: 0.9
  epochs: 100 #25 max 100 cifar10, 200 sinon
  decrease_lr_factor: 0.1
  decrease_lr_every: 50
  weight_decay: 0.00005
  beta1: 0.9
  beta2: 0.99
  warmup_epoch: 5
  DDP: False
  DP: True

mask:
    warmup_epoch: 20
    mask_ratio: 0.5
    jigsaw: 0.5
    num_masking_patches: 8
    min_num_patches: 2