path:
  data_path: '../data/cifar-100/'
  result_path: results/VIT_cifar100/
  model_path: Network/VIT_Model_cifar100/
  public_path: '../data/cinic-10/test/'

patch:
  image_size: 224
  patch_size: 16
  num_patches: 196
  num_classes: 100
  nums_per_class: [500, 100]
  nums_per_class_train: 500
  nums_per_class_val: 100
  channels: 3
  fold_size: 224
  fold_patch_size: 8
  embed_dim: 384
  depth: 12
  heads: 12
  mlp_dim: 512
  dropout: 0
  emb_dropout: 0.1

general:
  dataset: CIFAR100
  use_cuda: Yes
  seed: 1001
  seed_target: 1234
  seed_shadow: 101
  public_data_seed: 404
  train_target_size: 30000
  test_target_size: 30000
  channels: 3
  num_workers: 8
  mixup_alpha: 1
  cutmix_alpha: 1.0

#best 128 0.005/0.0055/0.006 0.034
#best 256 0.005/0.0055/0.006 0.034
#best 512 0.007 0.022
#best 1024 0.008/0.009/0.0085 0.021


learning:
  batch_size: 256
  learning_rate: 0.0006
  min_lr: 0.00001
  momentum: 0.9
  epochs: 40
  decrease_lr_factor: 1
  decrease_lr_every: 1
  weight_decay: 0.00005
  beta1: 0.9
  beta2: 0.99
  warmup_epoch: 5
  DDP: True
  DP: True
  atk_learning_rate: 0.001
  atk_epochs: 25

mask:
    start: 10
    step: 20
    stop: 196
    warmup_epoch: 5
    jigsaw: 0.5
    num_masking_patches: 8
    min_num_patches: 2
